name             'commitm-mysql'
maintainer       'minamijoyo'
maintainer_email 'minamijoyo@gmail.com'
license          'MIT'
description      'Customize mysql settings for commit-m'
long_description 'Customize mysql settings for commit-m'
version          '0.1.0'
depends          'mysql', '~> 6.1.0'
